branches:
  - main
  - name: dev
    prerelease: true

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  # - "@semantic-release/github"
  # - - "@semantic-release/exec"
    # - prepareCmd: "echo prepared"
      # publishCmd: "echo published"

