name: Release

on:
  push:
    branches:
      - main
      - dev

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install semantic-release (plugins)
        run: |
          npm install -g semantic-release/release-notes-generator

      - name: Create zip
        run: zip -r template.zip template/

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm exec semantic-release
