name: Release

on:
  push:
    branches:
      - main
      - dev
      #   prerelease: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Create zip
        run: zip -r template.zip template/

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
